# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
#多帐号YOUTH_HEADER 用#号隔开，其它的用&隔开
name: youth(中青看点)

on:
  workflow_dispatch:
  #schedule:
  #   - cron: '0/15 * * * *'
  watch:
    types: youth

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"
      # 安装依赖包
      - name: 安装依赖包
        run: npm install
        
      - name: '运行中青看点脚本'  
        run: node ./youth/youth.js.js
