name: 京喜财富岛

on:
  workflow_dispatch: # 手动触发
  schedule: # 计划任务触发
    - cron: '0 * * * *'
    # cron表达式，时区是UTC时间，比我们早8小时，如上所表示的是每天0点0分（24点整）
    # 建议每个人通过设置 GitHub Environments 的方式来设定为自己的目标运行时间（详细设置方法见文档说明）
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
            node-version: "12.x"
      # 安装依赖包
      - name: 安装依赖包
        run: npm install
        
      - name: '运行京喜财富岛脚本'  
        run: node ./JD_Scrip/jx_cfd.js
        
